### ISSUE TITLE
Version 1.2.0 checklist

### ISSUE THREAD

**Issue by supercam19** [supercam19/EnchantmentDetails#6]
A checklist of small additions, changes and fixes that I will be completing for the 1.2.0 update.

### Additions
- [x] Console logging for python scripts, such as when there's an error or to indicate that the files were successfully generated

### Changes
- [x] Change several enchantment descriptions to better represent what the enchantment does
- [x] Add a generate_pack.py script that generates all files for the datapack at once.
- [x] Empty output folder when running one of the generator scripts, so you don't have .mcfunction and .json files in the same folder at once
- [x] Add json formatting (indentations and newlines) to the generated advancement files
- README.md updates:
  - [x] Add install instructions
  - [x] Test compatible minecraft versions, and create list

### Fixes
- [x] Fix several enchantment descriptions with spelling mistakes
- [x] Fix sweeping edge not getting a description

More may be added before the 1.2.0 update is released.
